jobs:
  build:
    if: github.event.pull_request.head.repo.owner.login == 'jenkins-is-staging'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ secrets.PAT }}
    - continue-on-error: true
      name: Owner
      run: echo ${{ github.event.pull_request.head.repo.owner.login }}
    - continue-on-error: true
      name: Delete Fork Branch of wso2-jenkins-bot
      run: git push -d origin ${{ github.event.pull_request.head.ref }}
name: Fork Branch Deleter
on:
  repository_dispatch:
    types: trigger-ga___fork-branch-deleter.yml
