jobs:
  fossa-scan:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: fossas/fossa-action@main
      with:
        api-key: ${{secrets.FOSSAAPIKEY}}
name: FOSSA Scanner
on:
  repository_dispatch:
    types: trigger-ga___fossa-scanner.yaml
