env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3 -Djdk.util.zip.disableZip64ExtraFieldValidation=true
jobs:
  build:
    env:
      JAVA_TOOL_OPTIONS: -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Print Input
      run: echo Running the PR builder for PR - ${{ github.event.inputs.pr }}
    - continue-on-error: true
      name: Comment build info
      run: 'owner=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 4)

        repo=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 5)

        pr_number=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 7)

        curl -X POST https://api.github.com/repos/$owner/$repo/issues/$pr_number/comments
        -H ''Authorization: token ${{secrets.PR_BUILDER_COMMENT}}'' -d ''{"body":"PR
        builder started \nLink: https://github.com/wso2/product-is/actions/runs/${{github.run_id}}"}''

        '
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Adopt JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      id: java-8-setup
      name: Echo java 8 home
      run: 'echo "J8HOME=$JAVA_HOME" >> ${GITHUB_ENV}

        '
    - continue-on-error: true
      name: Set up Adopt JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Echo java 11 home
      run: 'echo "J11HOME=$JAVA_HOME" >> ${GITHUB_ENV}

        '
    - continue-on-error: true
      name: Build init
      run: 'echo "CURRENT_MONTH=$(date +%Y-%m)" >> ${GITHUB_ENV}

        '
    - continue-on-error: true
      id: cache-maven-m2
      name: Cache maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-pr-builder-${{ env.CURRENT_MONTH }}
        path: '~/.m2

          !~/.m2/repository/org/wso2/is/wso2is

          '
    - continue-on-error: true
      id: setup-pnpm
      name: Setup pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
        run_install: false
        version: latest
    - continue-on-error: true
      env:
        JAVA_11_HOME: ${{env.J11HOME}}
        JAVA_8_HOME: ${{env.J8HOME}}
        JDK_VERSION: ${{github.event.inputs.jdk}}
        PR_LINK: ${{github.event.inputs.pr}}
      id: builder_step
      name: Run PR builder
      run: 'wget https://raw.githubusercontent.com/wso2/product-is/master/.github/scripts/pr-builder.sh

        bash pr-builder.sh

        '
    - continue-on-error: true
      if: always()
      name: Archive PR diff file
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: repo-pr-diff
        path: '${{steps.builder_step.outputs.REPO_NAME}}/diff.diff

          '
    - continue-on-error: true
      if: always() && steps.builder_step.outputs.REPO_NAME != 'product-is'
      name: Archive repo mvn build log
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: repo-mvn-build-log
        path: '${{steps.builder_step.outputs.REPO_NAME}}/mvn-build.log

          '
    - continue-on-error: true
      if: always() && steps.builder_step.outputs.REPO_NAME != 'product-is'
      name: Archive repo surefire reports
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: repo-surefire-report
        path: '${{steps.builder_step.outputs.REPO_NAME}}/**/surefire-reports

          '
    - continue-on-error: true
      if: always()
      name: Archive product-is mvn build log
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: product-is-mvn-build-log
        path: 'product-is/mvn-build.log

          '
    - continue-on-error: true
      if: always()
      name: Archive product-is surefire reports
      uses: actions/upload-artifact@v2
      with:
        if-no-files-found: warn
        name: product-is-surefire-report
        path: 'product-is/**/surefire-reports

          '
    - continue-on-error: true
      if: always()
      name: Comment build status
      run: 'owner=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 4)

        repo=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 5)

        pr_number=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 7)

        curl -X POST https://api.github.com/repos/$owner/$repo/issues/$pr_number/comments
        -H ''Authorization: token ${{secrets.PR_BUILDER_COMMENT}}'' -d ''{"body":"PR
        builder completed \nLink: https://github.com/wso2/product-is/actions/runs/${{github.run_id}}
        \nStatus: **${{job.status}}**"}''

        '
    - continue-on-error: true
      if: success()
      name: Approve PR
      run: 'owner=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 4)

        repo=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 5)

        pr_number=$(echo ''${{github.event.inputs.pr}}'' | cut -d "/" -f 7)

        curl -X POST https://api.github.com/repos/$owner/$repo/pulls/$pr_number/reviews
        -H ''Authorization:token ${{secrets.PR_BUILDER_COMMENT}}'' -d ''{"body":"Approving
        the pull request based on the successful pr build https://github.com/wso2/product-is/actions/runs/${{github.run_id}}","event":"APPROVE"}''

        '
name: pr-builder-test
on:
  repository_dispatch:
    types: trigger-ga___pr-builder-test-JDK11.yml
