env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone product IS
      run: 'git clone https://github.com/wso2/product-is

        '
    - continue-on-error: true
      name: Set up Adopt JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Product-IS build with JDK 11 without Integration Tests
      run: 'cd product-is/

        mvn clean install --batch-mode -Dmaven.test.skip=true | tee mvn-build.log

        '
    - continue-on-error: true
      name: Set up Adopt JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Product-IS build with JDK 17 with Integration Tests
      run: "ls\ncd product-is/modules/integration/\nmvn clean install --batch-mode\
        \ | tee mvn-build.log\nPR_BUILD_STATUS=$(cat mvn-build.log | grep \"\\[INFO\\\
        ] BUILD\" | grep -oE '[^ ]+$')\nPR_TEST_RESULT=$(sed -n -e '/\\[INFO\\] Results:/,/\\\
        [INFO\\] Tests run:/ p' mvn-build.log)\nPR_BUILD_FINAL_RESULT=$(\n  echo \"\
        ===========================================================\"\n  echo \"product-is\
        \ BUILD $PR_BUILD_STATUS\"\n  echo \"==========================================================\"\
        \n  echo \"\"\n  echo \"$PR_TEST_RESULT\"\n)\nPR_BUILD_RESULT_LOG_TEMP=$(echo\
        \ \"$PR_BUILD_FINAL_RESULT\" | sed 's/$/%0A/')\nPR_BUILD_RESULT_LOG=$(echo\
        \ $PR_BUILD_RESULT_LOG_TEMP)\necho \"::warning::$PR_BUILD_RESULT_LOG\"\nPR_BUILD_SUCCESS_COUNT=$(grep\
        \ -o -i \"\\[INFO\\] BUILD SUCCESS\" mvn-build.log | wc -l)\nif [ \"$PR_BUILD_SUCCESS_COUNT\"\
        \ != \"3\" ]; then\n  echo \"PR BUILD not successfull. Aborting.\"\n  echo\
        \ \"::error::PR BUILD not successfull. Check artifacts for logs.\"\n  exit\
        \ 1\nfi\n"
name: product-is-builder-jdk17
on:
  repository_dispatch:
    types: trigger-ga___product-is-builder-jdk17.yml
